### PR TITLE
Check with context

### PR DESCRIPTION
**Pull request by moitias**
This PR adds context-aware lookups and a few new errors (NetworkError (eg. network not available) and TimeoutError)

Happy to work on it more, if you're not happy with how it looks / is implemented.

### CODE REVIEW

**Comment by smancke** [comment]
Cool, that was exactly the next improvement, I had in my mind!

- The PR now conflicts after my changed in the last merge.
- Also the build failed with an error from go vet.: check_test.go:105: the cancel function returned by context.WithTimeout should be called, not discarded, to avoid a context leak.

**Comment by moitias** [comment]
woops, looks like i overwrote your changes when merging, fixing.

**Comment by moitias** [comment]
This changes Result to only use constants, so the struct uses resultState now too. It sort of seems odd that the State field in the struct is public but the type is private, so no one can really compare that state to anything as they don't have a way of making resultStates. I think these should match and both be either private or public. 

If these were to be made private, then it would be possible to switch to using something else than strings to store state, but then that state would not be exported to JSON (although mailck the library doesn't seem to export any of the result state in JSON). It would also break API, which is a definite downside to it. 

If it's made public, it does seem a bit superfluous to me to have both the methods and the type; would result.Result == mailck.ValidState be better than result.IsValid()? Not sure myself. It sort of ties into the whole return value / error handling thing and opens another huge can of worms..

**Comment by smancke** [comment]
I changed the constant to be public. I would stay with strings, because the json handling stays to be simple. (The JSON is used by the mailckd subpackage, which is my main usecase)

I have merged the PR although it brakes the ability to try alternative mail servers from the MX list, because it returns in the loop and not breakes. But i guess, it is the best to cleanup the error thing, first. And do the fix the correct mx handling after that.

**Comment by moitias** [comment]
I started making a patch to fix that; but it occurred to me pretty quickly that the correct behaviour there is sort of un-defined too; what if the first we timeout to the first server and the second isn't actually an SMTP server and smtp.NewClinent() fails? What should we return? 

As this sort of ties into the whole rv/error thing and that seems like a bigger thing to deal with so I agree with you that it should be cleaned up first. I'll try to figure out some options at some point (the weekend, possibly) and open up an issue to discuss them if you don't mind - or open up one yourself first!

**Pull request merged**
