### PR TITLE
Add convenience methods and fix example in readme.MD

### PR DESCRIPTION
**Pull request by moitias**
Added some convenience methods to check the broad classification of the result (valid/invalid/error). The example in readme.MD was also not working so updated that to reflect the same concept with the new API. If you don't want to add the methods, will be happy to provide a PR with just a fixed example.

### CODE REVIEW

**Comment by smancke** [comment]
Hi moitias, thanks, looks great!
The coverage decreased, so please also cover the new functions in the tests.

**Comment by smancke** [comment]
thanks, just made the constant handling a litle bit more readable.

**Comment by moitias** [comment]
Any thoughts on where you feel the error handling should go? I think it's a bit weird that sometimes mailck returns errors _and_ failed results (return MailServerError,err), and sometimes no errors but failed results (return InvalidDomain,nil) anyway. 

From a users point of view, it's a bit confusing why I can't just check the error (if even required, in most cases i just want yes/no answers I guess) to see why it failed, but actually need to check for valid/invalid and if I do that then I can just as well check the error status from the same result and switch and don't really need the separate error. It's also duplicating the error state on two separate objects. (if result.iserror() then there is an err, otherwise not).

Any sort of change will probably be breaking, so I understand if you'd rather just leave it as it is.

**Comment by smancke** [comment]
I aggree: the best would be to move the error into the Result struct with a json:"-".

I don't see a breaking change in the api as a problem, for now, since the api is very new and not much clones, for now.

**Pull request merged**
